// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/metadata.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Metadata {
  public static partial class MetadataService
  {
    static readonly string __ServiceName = "metadata.MetadataService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Metadata.AddSongRequest> __Marshaller_metadata_AddSongRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Metadata.AddSongRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Metadata.SongResponse> __Marshaller_metadata_SongResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Metadata.SongResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Metadata.SongRequest> __Marshaller_metadata_SongRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Metadata.SongRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Metadata.SongPathResponse> __Marshaller_metadata_SongPathResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Metadata.SongPathResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Metadata.DeleteResponse> __Marshaller_metadata_DeleteResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Metadata.DeleteResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Metadata.SearchRequest> __Marshaller_metadata_SearchRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Metadata.SearchRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Metadata.SearchSongsResponse> __Marshaller_metadata_SearchSongsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Metadata.SearchSongsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Metadata.SearchArtistsResponse> __Marshaller_metadata_SearchArtistsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Metadata.SearchArtistsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Metadata.SearchAlbumsResponse> __Marshaller_metadata_SearchAlbumsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Metadata.SearchAlbumsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Metadata.SearchGenresResponse> __Marshaller_metadata_SearchGenresResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Metadata.SearchGenresResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Metadata.UpdateSongRequest> __Marshaller_metadata_UpdateSongRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Metadata.UpdateSongRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Metadata.GetAlbumByIdRequest> __Marshaller_metadata_GetAlbumByIdRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Metadata.GetAlbumByIdRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Metadata.GetAlbumByIdResponse> __Marshaller_metadata_GetAlbumByIdResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Metadata.GetAlbumByIdResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Metadata.UserPlayRequest> __Marshaller_metadata_UserPlayRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Metadata.UserPlayRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Metadata.UserPlayResponse> __Marshaller_metadata_UserPlayResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Metadata.UserPlayResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Metadata.UserStatisticsRequest> __Marshaller_metadata_UserStatisticsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Metadata.UserStatisticsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Metadata.UserStatisticsResponse> __Marshaller_metadata_UserStatisticsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Metadata.UserStatisticsResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Metadata.AddSongRequest, global::Metadata.SongResponse> __Method_AddSong = new grpc::Method<global::Metadata.AddSongRequest, global::Metadata.SongResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddSong",
        __Marshaller_metadata_AddSongRequest,
        __Marshaller_metadata_SongResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Metadata.SongRequest, global::Metadata.SongResponse> __Method_GetSongMetadata = new grpc::Method<global::Metadata.SongRequest, global::Metadata.SongResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetSongMetadata",
        __Marshaller_metadata_SongRequest,
        __Marshaller_metadata_SongResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Metadata.SongRequest, global::Metadata.SongPathResponse> __Method_GetSongPath = new grpc::Method<global::Metadata.SongRequest, global::Metadata.SongPathResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetSongPath",
        __Marshaller_metadata_SongRequest,
        __Marshaller_metadata_SongPathResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Metadata.SongRequest, global::Metadata.DeleteResponse> __Method_DeleteSong = new grpc::Method<global::Metadata.SongRequest, global::Metadata.DeleteResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteSong",
        __Marshaller_metadata_SongRequest,
        __Marshaller_metadata_DeleteResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Metadata.SearchRequest, global::Metadata.SearchSongsResponse> __Method_SearchSongs = new grpc::Method<global::Metadata.SearchRequest, global::Metadata.SearchSongsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SearchSongs",
        __Marshaller_metadata_SearchRequest,
        __Marshaller_metadata_SearchSongsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Metadata.SearchRequest, global::Metadata.SearchArtistsResponse> __Method_SearchArtists = new grpc::Method<global::Metadata.SearchRequest, global::Metadata.SearchArtistsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SearchArtists",
        __Marshaller_metadata_SearchRequest,
        __Marshaller_metadata_SearchArtistsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Metadata.SearchRequest, global::Metadata.SearchAlbumsResponse> __Method_SearchAlbums = new grpc::Method<global::Metadata.SearchRequest, global::Metadata.SearchAlbumsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SearchAlbums",
        __Marshaller_metadata_SearchRequest,
        __Marshaller_metadata_SearchAlbumsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Metadata.SearchRequest, global::Metadata.SearchGenresResponse> __Method_SearchGenres = new grpc::Method<global::Metadata.SearchRequest, global::Metadata.SearchGenresResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SearchGenres",
        __Marshaller_metadata_SearchRequest,
        __Marshaller_metadata_SearchGenresResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Metadata.UpdateSongRequest, global::Metadata.SongResponse> __Method_UpdateSong = new grpc::Method<global::Metadata.UpdateSongRequest, global::Metadata.SongResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateSong",
        __Marshaller_metadata_UpdateSongRequest,
        __Marshaller_metadata_SongResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Metadata.GetAlbumByIdRequest, global::Metadata.GetAlbumByIdResponse> __Method_GetAlbumById = new grpc::Method<global::Metadata.GetAlbumByIdRequest, global::Metadata.GetAlbumByIdResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAlbumById",
        __Marshaller_metadata_GetAlbumByIdRequest,
        __Marshaller_metadata_GetAlbumByIdResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Metadata.UserPlayRequest, global::Metadata.UserPlayResponse> __Method_RegisterUserPlay = new grpc::Method<global::Metadata.UserPlayRequest, global::Metadata.UserPlayResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RegisterUserPlay",
        __Marshaller_metadata_UserPlayRequest,
        __Marshaller_metadata_UserPlayResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Metadata.UserStatisticsRequest, global::Metadata.UserStatisticsResponse> __Method_GetUserStatistics = new grpc::Method<global::Metadata.UserStatisticsRequest, global::Metadata.UserStatisticsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetUserStatistics",
        __Marshaller_metadata_UserStatisticsRequest,
        __Marshaller_metadata_UserStatisticsResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Metadata.MetadataReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of MetadataService</summary>
    [grpc::BindServiceMethod(typeof(MetadataService), "BindService")]
    public abstract partial class MetadataServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Metadata.SongResponse> AddSong(global::Metadata.AddSongRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Metadata.SongResponse> GetSongMetadata(global::Metadata.SongRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Metadata.SongPathResponse> GetSongPath(global::Metadata.SongRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Metadata.DeleteResponse> DeleteSong(global::Metadata.SongRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Metadata.SearchSongsResponse> SearchSongs(global::Metadata.SearchRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Metadata.SearchArtistsResponse> SearchArtists(global::Metadata.SearchRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Metadata.SearchAlbumsResponse> SearchAlbums(global::Metadata.SearchRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Metadata.SearchGenresResponse> SearchGenres(global::Metadata.SearchRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Metadata.SongResponse> UpdateSong(global::Metadata.UpdateSongRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Metadata.GetAlbumByIdResponse> GetAlbumById(global::Metadata.GetAlbumByIdRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Metadata.UserPlayResponse> RegisterUserPlay(global::Metadata.UserPlayRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Metadata.UserStatisticsResponse> GetUserStatistics(global::Metadata.UserStatisticsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for MetadataService</summary>
    public partial class MetadataServiceClient : grpc::ClientBase<MetadataServiceClient>
    {
      /// <summary>Creates a new client for MetadataService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public MetadataServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for MetadataService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public MetadataServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected MetadataServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected MetadataServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Metadata.SongResponse AddSong(global::Metadata.AddSongRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddSong(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Metadata.SongResponse AddSong(global::Metadata.AddSongRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddSong, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Metadata.SongResponse> AddSongAsync(global::Metadata.AddSongRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddSongAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Metadata.SongResponse> AddSongAsync(global::Metadata.AddSongRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddSong, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Metadata.SongResponse GetSongMetadata(global::Metadata.SongRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSongMetadata(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Metadata.SongResponse GetSongMetadata(global::Metadata.SongRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetSongMetadata, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Metadata.SongResponse> GetSongMetadataAsync(global::Metadata.SongRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSongMetadataAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Metadata.SongResponse> GetSongMetadataAsync(global::Metadata.SongRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetSongMetadata, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Metadata.SongPathResponse GetSongPath(global::Metadata.SongRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSongPath(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Metadata.SongPathResponse GetSongPath(global::Metadata.SongRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetSongPath, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Metadata.SongPathResponse> GetSongPathAsync(global::Metadata.SongRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSongPathAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Metadata.SongPathResponse> GetSongPathAsync(global::Metadata.SongRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetSongPath, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Metadata.DeleteResponse DeleteSong(global::Metadata.SongRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteSong(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Metadata.DeleteResponse DeleteSong(global::Metadata.SongRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteSong, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Metadata.DeleteResponse> DeleteSongAsync(global::Metadata.SongRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteSongAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Metadata.DeleteResponse> DeleteSongAsync(global::Metadata.SongRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteSong, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Metadata.SearchSongsResponse SearchSongs(global::Metadata.SearchRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SearchSongs(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Metadata.SearchSongsResponse SearchSongs(global::Metadata.SearchRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SearchSongs, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Metadata.SearchSongsResponse> SearchSongsAsync(global::Metadata.SearchRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SearchSongsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Metadata.SearchSongsResponse> SearchSongsAsync(global::Metadata.SearchRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SearchSongs, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Metadata.SearchArtistsResponse SearchArtists(global::Metadata.SearchRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SearchArtists(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Metadata.SearchArtistsResponse SearchArtists(global::Metadata.SearchRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SearchArtists, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Metadata.SearchArtistsResponse> SearchArtistsAsync(global::Metadata.SearchRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SearchArtistsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Metadata.SearchArtistsResponse> SearchArtistsAsync(global::Metadata.SearchRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SearchArtists, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Metadata.SearchAlbumsResponse SearchAlbums(global::Metadata.SearchRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SearchAlbums(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Metadata.SearchAlbumsResponse SearchAlbums(global::Metadata.SearchRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SearchAlbums, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Metadata.SearchAlbumsResponse> SearchAlbumsAsync(global::Metadata.SearchRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SearchAlbumsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Metadata.SearchAlbumsResponse> SearchAlbumsAsync(global::Metadata.SearchRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SearchAlbums, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Metadata.SearchGenresResponse SearchGenres(global::Metadata.SearchRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SearchGenres(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Metadata.SearchGenresResponse SearchGenres(global::Metadata.SearchRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SearchGenres, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Metadata.SearchGenresResponse> SearchGenresAsync(global::Metadata.SearchRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SearchGenresAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Metadata.SearchGenresResponse> SearchGenresAsync(global::Metadata.SearchRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SearchGenres, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Metadata.SongResponse UpdateSong(global::Metadata.UpdateSongRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateSong(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Metadata.SongResponse UpdateSong(global::Metadata.UpdateSongRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateSong, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Metadata.SongResponse> UpdateSongAsync(global::Metadata.UpdateSongRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateSongAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Metadata.SongResponse> UpdateSongAsync(global::Metadata.UpdateSongRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateSong, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Metadata.GetAlbumByIdResponse GetAlbumById(global::Metadata.GetAlbumByIdRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAlbumById(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Metadata.GetAlbumByIdResponse GetAlbumById(global::Metadata.GetAlbumByIdRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAlbumById, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Metadata.GetAlbumByIdResponse> GetAlbumByIdAsync(global::Metadata.GetAlbumByIdRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAlbumByIdAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Metadata.GetAlbumByIdResponse> GetAlbumByIdAsync(global::Metadata.GetAlbumByIdRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAlbumById, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Metadata.UserPlayResponse RegisterUserPlay(global::Metadata.UserPlayRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RegisterUserPlay(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Metadata.UserPlayResponse RegisterUserPlay(global::Metadata.UserPlayRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RegisterUserPlay, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Metadata.UserPlayResponse> RegisterUserPlayAsync(global::Metadata.UserPlayRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RegisterUserPlayAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Metadata.UserPlayResponse> RegisterUserPlayAsync(global::Metadata.UserPlayRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RegisterUserPlay, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Metadata.UserStatisticsResponse GetUserStatistics(global::Metadata.UserStatisticsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetUserStatistics(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Metadata.UserStatisticsResponse GetUserStatistics(global::Metadata.UserStatisticsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetUserStatistics, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Metadata.UserStatisticsResponse> GetUserStatisticsAsync(global::Metadata.UserStatisticsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetUserStatisticsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Metadata.UserStatisticsResponse> GetUserStatisticsAsync(global::Metadata.UserStatisticsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetUserStatistics, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override MetadataServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new MetadataServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(MetadataServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_AddSong, serviceImpl.AddSong)
          .AddMethod(__Method_GetSongMetadata, serviceImpl.GetSongMetadata)
          .AddMethod(__Method_GetSongPath, serviceImpl.GetSongPath)
          .AddMethod(__Method_DeleteSong, serviceImpl.DeleteSong)
          .AddMethod(__Method_SearchSongs, serviceImpl.SearchSongs)
          .AddMethod(__Method_SearchArtists, serviceImpl.SearchArtists)
          .AddMethod(__Method_SearchAlbums, serviceImpl.SearchAlbums)
          .AddMethod(__Method_SearchGenres, serviceImpl.SearchGenres)
          .AddMethod(__Method_UpdateSong, serviceImpl.UpdateSong)
          .AddMethod(__Method_GetAlbumById, serviceImpl.GetAlbumById)
          .AddMethod(__Method_RegisterUserPlay, serviceImpl.RegisterUserPlay)
          .AddMethod(__Method_GetUserStatistics, serviceImpl.GetUserStatistics).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, MetadataServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_AddSong, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Metadata.AddSongRequest, global::Metadata.SongResponse>(serviceImpl.AddSong));
      serviceBinder.AddMethod(__Method_GetSongMetadata, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Metadata.SongRequest, global::Metadata.SongResponse>(serviceImpl.GetSongMetadata));
      serviceBinder.AddMethod(__Method_GetSongPath, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Metadata.SongRequest, global::Metadata.SongPathResponse>(serviceImpl.GetSongPath));
      serviceBinder.AddMethod(__Method_DeleteSong, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Metadata.SongRequest, global::Metadata.DeleteResponse>(serviceImpl.DeleteSong));
      serviceBinder.AddMethod(__Method_SearchSongs, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Metadata.SearchRequest, global::Metadata.SearchSongsResponse>(serviceImpl.SearchSongs));
      serviceBinder.AddMethod(__Method_SearchArtists, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Metadata.SearchRequest, global::Metadata.SearchArtistsResponse>(serviceImpl.SearchArtists));
      serviceBinder.AddMethod(__Method_SearchAlbums, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Metadata.SearchRequest, global::Metadata.SearchAlbumsResponse>(serviceImpl.SearchAlbums));
      serviceBinder.AddMethod(__Method_SearchGenres, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Metadata.SearchRequest, global::Metadata.SearchGenresResponse>(serviceImpl.SearchGenres));
      serviceBinder.AddMethod(__Method_UpdateSong, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Metadata.UpdateSongRequest, global::Metadata.SongResponse>(serviceImpl.UpdateSong));
      serviceBinder.AddMethod(__Method_GetAlbumById, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Metadata.GetAlbumByIdRequest, global::Metadata.GetAlbumByIdResponse>(serviceImpl.GetAlbumById));
      serviceBinder.AddMethod(__Method_RegisterUserPlay, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Metadata.UserPlayRequest, global::Metadata.UserPlayResponse>(serviceImpl.RegisterUserPlay));
      serviceBinder.AddMethod(__Method_GetUserStatistics, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Metadata.UserStatisticsRequest, global::Metadata.UserStatisticsResponse>(serviceImpl.GetUserStatistics));
    }

  }
}
#endregion
